# SPDX-License-Identifier: GPL-3.0-or-later
import struct
import tempfile
import unittest
from pathlib import Path

from btrfs_patrol.boot import (
    installed_kernel_versions,
    parse_bls_entry,
    stale_kernel_versions,
    uki_version,
)

ENTRY = """\
# Generated by kernel-install
title   Fedora Linux (6.17.1-300.fc44.x86_64) 44 (Workstation Edition)
version 6.17.1-300.fc44.x86_64
linux   /vmlinuz-6.17.1-300.fc44.x86_64
initrd  /initramfs-6.17.1-300.fc44.x86_64.img
options root=UUID=4a9371b2 ro rootflags=subvol=root
"""
MACHINE_ID = "0108a8f87e784af98bf70815ff87d439"


def make_pe(sections):
    """A minimal PE file: DOS header, PE signature, COFF header, section table, data."""
    pe_offset = 0x40
    dos = bytearray(pe_offset)
    dos[0:2] = b"MZ"
    struct.pack_into("<I", dos, 0x3C, pe_offset)
    # Machine, NumberOfSections, TimeDateStamp, PointerToSymbolTable, NumberOfSymbols,
    # SizeOfOptionalHeader, Characteristics
    coff = b"PE\0\0" + struct.pack("<HHIIIHH", 0x8664, len(sections), 0, 0, 0, 0, 0x0206)
    data_start = pe_offset + 24 + 40 * len(sections)
    table, body = b"", b""
    for name, data in sections:
        table += name.encode().ljust(8, b"\0") + struct.pack(
            "<IIIIIIHHI", len(data), 0x1000, len(data), data_start + len(body), 0, 0, 0, 0, 0
        )
        body += data
    return bytes(dos) + coff + table + body


def linux_image(version_string):
    """A .linux section with the boot protocol's setup header and version string."""
    image = bytearray(0x400)
    image[0x202:0x206] = b"HdrS"
    struct.pack_into("<H", image, 0x20E, 0x100)
    text = version_string.encode() + b"\0"
    image[0x300 : 0x300 + len(text)] = text
    return bytes(image)


class BlsEntryTests(unittest.TestCase):
    def test_parse_entry(self):
        entry = parse_bls_entry(ENTRY)
        self.assertEqual(entry["version"], "6.17.1-300.fc44.x86_64")
        self.assertEqual(entry["title"], "Fedora Linux (6.17.1-300.fc44.x86_64) 44 (Workstation Edition)")
        self.assertEqual(entry["options"], "root=UUID=4a9371b2 ro rootflags=subvol=root")

    def test_installed_kernel_versions(self):
        with tempfile.TemporaryDirectory() as tmp:
            entries = Path(tmp)
            (entries / "a-6.17.1.conf").write_text(ENTRY)
            (entries / "b-6.16.9.conf").write_text(ENTRY.replace("6.17.1-300", "6.16.9-200"))
            (entries / "rescue.conf").write_text("title Rescue\n")
            # The rescue entry Fedora's installer writes for GRUB names no kernel version.
            (entries / f"{MACHINE_ID}-0-rescue.conf").write_text(
                f"title Fedora Linux (0-rescue-{MACHINE_ID}) 44 (Workstation Edition)\n"
                f"version 0-rescue-{MACHINE_ID}\n"
                f"linux /vmlinuz-0-rescue-{MACHINE_ID}\n"
            )
            (entries / "notes.txt").write_text("version 1.0\n")
            self.assertEqual(
                installed_kernel_versions(entries, esp_mounts=()),
                {"6.17.1-300.fc44.x86_64", "6.16.9-200.fc44.x86_64"},
            )

    def test_missing_everything(self):
        self.assertEqual(
            installed_kernel_versions(Path("/nonexistent/loader/entries"), esp_mounts=[Path("/nonexistent")]),
            set(),
        )


class UkiTests(unittest.TestCase):
    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.dir = Path(tmp.name)

    def write(self, name, data):
        path = self.dir / name
        path.write_bytes(data)
        return path

    def test_version_from_the_uname_section(self):
        image = make_pe([
            (".osrel", b"NAME=Fedora Linux\n"),
            (".uname", b"7.2.5-200.fc44.x86_64\0\0\0"),
            (".linux", linux_image("7.2.4-100.fc44.x86_64 (mockbuild@fedora) #1 SMP")),
        ])
        # The section wins over both the kernel header and a different file name.
        path = self.write(f"{MACHINE_ID}-7.2.3-1.fc44.x86_64.efi", image)
        self.assertEqual(uki_version(path), "7.2.5-200.fc44.x86_64")

    def test_version_from_the_kernel_header_without_uname(self):
        image = make_pe([
            (".osrel", b"NAME=Fedora Linux\n"),
            (".linux", linux_image("7.2.5-200.fc44.x86_64 (mockbuild@fedora) #1 SMP PREEMPT_DYNAMIC")),
        ])
        self.assertEqual(uki_version(self.write("linux.efi", image)), "7.2.5-200.fc44.x86_64")

    def test_version_from_the_file_name_last(self):
        path = self.write(f"{MACHINE_ID}-7.2.4-200.fc44.x86_64+3-0.efi", b"not a PE file")
        self.assertEqual(uki_version(path), "7.2.4-200.fc44.x86_64")

    def test_nothing_to_go_by(self):
        truncated = make_pe([(".uname", b"7.2.5-200.fc44.x86_64\0")])[:70]
        self.assertIsNone(uki_version(self.write("broken.efi", truncated)))
        not_a_version = make_pe([(".uname", b"hello world\0")])
        self.assertIsNone(uki_version(self.write("linux.efi", not_a_version)))
        huge_count = bytearray(make_pe([]))
        struct.pack_into("<H", huge_count, 0x40 + 6, 60000)
        self.assertIsNone(uki_version(self.write("odd.efi", bytes(huge_count))))
        self.assertIsNone(uki_version(self.dir / "missing.efi"))

    def test_both_entry_types_are_combined(self):
        entries = self.dir / "loader/entries"
        entries.mkdir(parents=True)
        (entries / "a.conf").write_text(ENTRY)
        uki_dir = self.dir / "esp/EFI/Linux"
        uki_dir.mkdir(parents=True)
        (uki_dir / f"{MACHINE_ID}-7.2.5-200.fc44.x86_64.efi").write_bytes(
            make_pe([(".uname", b"7.2.5-200.fc44.x86_64\0")])
        )
        (uki_dir / "README.txt").write_text("7.9.9-1.fc44.x86_64")
        esp = self.dir / "esp"
        self.assertEqual(
            # The same partition listed twice, as /boot and /boot/efi can be, counts once.
            installed_kernel_versions(entries, esp_mounts=[esp, esp, self.dir / "none"]),
            {"6.17.1-300.fc44.x86_64", "7.2.5-200.fc44.x86_64"},
        )

    def test_ukis_alone(self):
        uki_dir = self.dir / "EFI/Linux"
        uki_dir.mkdir(parents=True)
        (uki_dir / "fedora-7.2.5-200.fc44.x86_64.efi").write_bytes(b"\0" * 16)
        self.assertEqual(
            installed_kernel_versions(self.dir / "loader/entries", esp_mounts=[self.dir]),
            {"7.2.5-200.fc44.x86_64"},
        )


if __name__ == "__main__":
    unittest.main()


class StaleKernelTests(unittest.TestCase):
    """Boot entries whose kernel has no modules: what a rollback leaves behind."""

    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        base = Path(tmp.name)
        self.entries = base / "entries"
        self.entries.mkdir()
        self.modules = base / "modules"
        self.modules.mkdir()

    def entry(self, version):
        text = ENTRY.replace("6.17.1-300.fc44.x86_64", version)
        (self.entries / f"{MACHINE_ID}-{version}.conf").write_text(text)

    def stale(self):
        # No ESP mounts: this test only exercises Type #1 entries.
        return stale_kernel_versions(self.modules, self.entries, ())

    def test_an_entry_without_modules_is_stale(self):
        self.entry("6.17.1-300.fc44.x86_64")
        self.entry("6.18.0-300.fc45.x86_64")
        (self.modules / "6.17.1-300.fc44.x86_64").mkdir()
        self.assertEqual(self.stale(), {"6.18.0-300.fc45.x86_64"})

    def test_nothing_is_stale_when_every_entry_has_modules(self):
        self.entry("6.17.1-300.fc44.x86_64")
        (self.modules / "6.17.1-300.fc44.x86_64").mkdir()
        self.assertEqual(self.stale(), set())

    def test_no_entries_means_nothing_stale(self):
        (self.modules / "6.17.1-300.fc44.x86_64").mkdir()
        self.assertEqual(self.stale(), set())

    def test_a_file_that_is_not_a_directory_does_not_count_as_modules(self):
        self.entry("6.18.0-300.fc45.x86_64")
        (self.modules / "6.18.0-300.fc45.x86_64").write_text("not a directory")
        self.assertEqual(self.stale(), {"6.18.0-300.fc45.x86_64"})
