# SPDX-License-Identifier: GPL-3.0-or-later
import tempfile
import unittest
from pathlib import Path

from btrfs_patrol.boot import installed_kernel_versions, parse_bls_entry

ENTRY = """\
# Generated by kernel-install
title   Fedora Linux (6.17.1-300.fc44.x86_64) 44 (Workstation Edition)
version 6.17.1-300.fc44.x86_64
linux   /vmlinuz-6.17.1-300.fc44.x86_64
initrd  /initramfs-6.17.1-300.fc44.x86_64.img
options root=UUID=4a9371b2 ro rootflags=subvol=root
"""


class BootTests(unittest.TestCase):
    def test_parse_entry(self):
        entry = parse_bls_entry(ENTRY)
        self.assertEqual(entry["version"], "6.17.1-300.fc44.x86_64")
        self.assertEqual(entry["title"], "Fedora Linux (6.17.1-300.fc44.x86_64) 44 (Workstation Edition)")
        self.assertEqual(entry["options"], "root=UUID=4a9371b2 ro rootflags=subvol=root")

    def test_installed_kernel_versions(self):
        with tempfile.TemporaryDirectory() as tmp:
            entries = Path(tmp)
            (entries / "a-6.17.1.conf").write_text(ENTRY)
            (entries / "b-6.16.9.conf").write_text(ENTRY.replace("6.17.1-300", "6.16.9-200"))
            (entries / "rescue.conf").write_text("title Rescue\n")
            (entries / "notes.txt").write_text("version 1.0\n")
            self.assertEqual(
                installed_kernel_versions(entries),
                {"6.17.1-300.fc44.x86_64", "6.16.9-200.fc44.x86_64"},
            )

    def test_missing_entries_directory(self):
        self.assertEqual(installed_kernel_versions(Path("/nonexistent/loader/entries")), set())


if __name__ == "__main__":
    unittest.main()
