# SPDX-License-Identifier: GPL-3.0-or-later
import struct
import tempfile
import unittest
from pathlib import Path

from btrfs_patrol import boot
from btrfs_patrol.boot import (
    ENTRY_PREFIX,
    entry_text,
    kernel_files,
    snapshot_entries,
    snapshot_options,
    sync_snapshot_entries,
    installed_kernel_versions,
    parse_bls_entry,
    stale_kernel_versions,
    uki_version,
)

ENTRY = """\
# Generated by kernel-install
title   Fedora Linux (6.17.1-300.fc44.x86_64) 44 (Workstation Edition)
version 6.17.1-300.fc44.x86_64
linux   /vmlinuz-6.17.1-300.fc44.x86_64
initrd  /initramfs-6.17.1-300.fc44.x86_64.img
options root=UUID=4a9371b2 ro rootflags=subvol=root
"""
MACHINE_ID = "0108a8f87e784af98bf70815ff87d439"


def make_pe(sections):
    """A minimal PE file: DOS header, PE signature, COFF header, section table, data."""
    pe_offset = 0x40
    dos = bytearray(pe_offset)
    dos[0:2] = b"MZ"
    struct.pack_into("<I", dos, 0x3C, pe_offset)
    # Machine, NumberOfSections, TimeDateStamp, PointerToSymbolTable, NumberOfSymbols,
    # SizeOfOptionalHeader, Characteristics
    coff = b"PE\0\0" + struct.pack("<HHIIIHH", 0x8664, len(sections), 0, 0, 0, 0, 0x0206)
    data_start = pe_offset + 24 + 40 * len(sections)
    table, body = b"", b""
    for name, data in sections:
        table += name.encode().ljust(8, b"\0") + struct.pack(
            "<IIIIIIHHI", len(data), 0x1000, len(data), data_start + len(body), 0, 0, 0, 0, 0
        )
        body += data
    return bytes(dos) + coff + table + body


def linux_image(version_string):
    """A .linux section with the boot protocol's setup header and version string."""
    image = bytearray(0x400)
    image[0x202:0x206] = b"HdrS"
    struct.pack_into("<H", image, 0x20E, 0x100)
    text = version_string.encode() + b"\0"
    image[0x300 : 0x300 + len(text)] = text
    return bytes(image)


class BlsEntryTests(unittest.TestCase):
    def test_parse_entry(self):
        entry = parse_bls_entry(ENTRY)
        self.assertEqual(entry["version"], "6.17.1-300.fc44.x86_64")
        self.assertEqual(entry["title"], "Fedora Linux (6.17.1-300.fc44.x86_64) 44 (Workstation Edition)")
        self.assertEqual(entry["options"], "root=UUID=4a9371b2 ro rootflags=subvol=root")

    def test_installed_kernel_versions(self):
        with tempfile.TemporaryDirectory() as tmp:
            entries = Path(tmp)
            (entries / "a-6.17.1.conf").write_text(ENTRY)
            (entries / "b-6.16.9.conf").write_text(ENTRY.replace("6.17.1-300", "6.16.9-200"))
            (entries / "rescue.conf").write_text("title Rescue\n")
            # The rescue entry Fedora's installer writes for GRUB names no kernel version.
            (entries / f"{MACHINE_ID}-0-rescue.conf").write_text(
                f"title Fedora Linux (0-rescue-{MACHINE_ID}) 44 (Workstation Edition)\n"
                f"version 0-rescue-{MACHINE_ID}\n"
                f"linux /vmlinuz-0-rescue-{MACHINE_ID}\n"
            )
            (entries / "notes.txt").write_text("version 1.0\n")
            self.assertEqual(
                installed_kernel_versions(entries, esp_mounts=()),
                {"6.17.1-300.fc44.x86_64", "6.16.9-200.fc44.x86_64"},
            )

    def test_missing_everything(self):
        self.assertEqual(
            installed_kernel_versions(Path("/nonexistent/loader/entries"), esp_mounts=[Path("/nonexistent")]),
            set(),
        )


class UkiTests(unittest.TestCase):
    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.dir = Path(tmp.name)

    def write(self, name, data):
        path = self.dir / name
        path.write_bytes(data)
        return path

    def test_version_from_the_uname_section(self):
        image = make_pe([
            (".osrel", b"NAME=Fedora Linux\n"),
            (".uname", b"7.2.5-200.fc44.x86_64\0\0\0"),
            (".linux", linux_image("7.2.4-100.fc44.x86_64 (mockbuild@fedora) #1 SMP")),
        ])
        # The section wins over both the kernel header and a different file name.
        path = self.write(f"{MACHINE_ID}-7.2.3-1.fc44.x86_64.efi", image)
        self.assertEqual(uki_version(path), "7.2.5-200.fc44.x86_64")

    def test_version_from_the_kernel_header_without_uname(self):
        image = make_pe([
            (".osrel", b"NAME=Fedora Linux\n"),
            (".linux", linux_image("7.2.5-200.fc44.x86_64 (mockbuild@fedora) #1 SMP PREEMPT_DYNAMIC")),
        ])
        self.assertEqual(uki_version(self.write("linux.efi", image)), "7.2.5-200.fc44.x86_64")

    def test_version_from_the_file_name_last(self):
        path = self.write(f"{MACHINE_ID}-7.2.4-200.fc44.x86_64+3-0.efi", b"not a PE file")
        self.assertEqual(uki_version(path), "7.2.4-200.fc44.x86_64")

    def test_nothing_to_go_by(self):
        truncated = make_pe([(".uname", b"7.2.5-200.fc44.x86_64\0")])[:70]
        self.assertIsNone(uki_version(self.write("broken.efi", truncated)))
        not_a_version = make_pe([(".uname", b"hello world\0")])
        self.assertIsNone(uki_version(self.write("linux.efi", not_a_version)))
        huge_count = bytearray(make_pe([]))
        struct.pack_into("<H", huge_count, 0x40 + 6, 60000)
        self.assertIsNone(uki_version(self.write("odd.efi", bytes(huge_count))))
        self.assertIsNone(uki_version(self.dir / "missing.efi"))

    def test_both_entry_types_are_combined(self):
        entries = self.dir / "loader/entries"
        entries.mkdir(parents=True)
        (entries / "a.conf").write_text(ENTRY)
        uki_dir = self.dir / "esp/EFI/Linux"
        uki_dir.mkdir(parents=True)
        (uki_dir / f"{MACHINE_ID}-7.2.5-200.fc44.x86_64.efi").write_bytes(
            make_pe([(".uname", b"7.2.5-200.fc44.x86_64\0")])
        )
        (uki_dir / "README.txt").write_text("7.9.9-1.fc44.x86_64")
        esp = self.dir / "esp"
        self.assertEqual(
            # The same partition listed twice, as /boot and /boot/efi can be, counts once.
            installed_kernel_versions(entries, esp_mounts=[esp, esp, self.dir / "none"]),
            {"6.17.1-300.fc44.x86_64", "7.2.5-200.fc44.x86_64"},
        )

    def test_ukis_alone(self):
        uki_dir = self.dir / "EFI/Linux"
        uki_dir.mkdir(parents=True)
        (uki_dir / "fedora-7.2.5-200.fc44.x86_64.efi").write_bytes(b"\0" * 16)
        self.assertEqual(
            installed_kernel_versions(self.dir / "loader/entries", esp_mounts=[self.dir]),
            {"7.2.5-200.fc44.x86_64"},
        )


if __name__ == "__main__":
    unittest.main()


class StaleKernelTests(unittest.TestCase):
    """Boot entries whose kernel has no modules: what a rollback leaves behind."""

    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        base = Path(tmp.name)
        self.entries = base / "entries"
        self.entries.mkdir()
        self.modules = base / "modules"
        self.modules.mkdir()

    def entry(self, version):
        text = ENTRY.replace("6.17.1-300.fc44.x86_64", version)
        (self.entries / f"{MACHINE_ID}-{version}.conf").write_text(text)

    def stale(self):
        # No ESP mounts: this test only exercises Type #1 entries.
        return stale_kernel_versions(self.modules, self.entries, ())

    def test_an_entry_without_modules_is_stale(self):
        self.entry("6.17.1-300.fc44.x86_64")
        self.entry("6.18.0-300.fc45.x86_64")
        (self.modules / "6.17.1-300.fc44.x86_64").mkdir()
        self.assertEqual(self.stale(), {"6.18.0-300.fc45.x86_64"})

    def test_nothing_is_stale_when_every_entry_has_modules(self):
        self.entry("6.17.1-300.fc44.x86_64")
        (self.modules / "6.17.1-300.fc44.x86_64").mkdir()
        self.assertEqual(self.stale(), set())

    def test_no_entries_means_nothing_stale(self):
        (self.modules / "6.17.1-300.fc44.x86_64").mkdir()
        self.assertEqual(self.stale(), set())

    def test_a_file_that_is_not_a_directory_does_not_count_as_modules(self):
        self.entry("6.18.0-300.fc45.x86_64")
        (self.modules / "6.18.0-300.fc45.x86_64").write_text("not a directory")
        self.assertEqual(self.stale(), {"6.18.0-300.fc45.x86_64"})


class BootPartitionLocationTests(unittest.TestCase):
    """Type #1 entries live under $BOOT, which is not always /boot."""

    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.base = Path(tmp.name)

    def entry(self, directory, version):
        directory.mkdir(parents=True, exist_ok=True)
        (directory / f"{MACHINE_ID}-{version}.conf").write_text(
            ENTRY.replace("6.17.1-300.fc44.x86_64", version)
        )

    def test_entries_on_an_esp_mounted_at_efi_are_found(self):
        esp = self.base / "efi"
        self.entry(esp / "loader/entries", "6.18.0-300.fc45.x86_64")
        found = installed_kernel_versions(self.base / "boot/loader/entries", (esp,))
        self.assertEqual(found, {"6.18.0-300.fc45.x86_64"})

    def test_the_traditional_location_still_works(self):
        entries = self.base / "boot/loader/entries"
        self.entry(entries, "6.17.1-300.fc44.x86_64")
        self.assertEqual(installed_kernel_versions(entries, ()), {"6.17.1-300.fc44.x86_64"})

    def test_the_same_directory_reached_twice_is_not_counted_twice(self):
        boot = self.base / "boot"
        self.entry(boot / "loader/entries", "6.17.1-300.fc44.x86_64")
        found = installed_kernel_versions(boot / "loader/entries", (boot,))
        self.assertEqual(found, {"6.17.1-300.fc44.x86_64"})

    def test_an_unreadable_entry_is_skipped_not_fatal(self):
        entries = self.base / "boot/loader/entries"
        entries.mkdir(parents=True)
        (entries / "broken.conf").write_bytes(b"version \xff\xfe not-utf8\n")
        self.entry(entries, "6.17.1-300.fc44.x86_64")
        self.assertEqual(installed_kernel_versions(entries, ()), {"6.17.1-300.fc44.x86_64"})


class SnapshotOptionsTests(unittest.TestCase):
    """The snapshot's command line is derived from the running one, not invented."""

    LUKS = ("BOOT_IMAGE=/vmlinuz root=UUID=4a93 ro rootflags=subvol=root,compress=zstd:1 "
            "rd.luks.uuid=luks-3f24 rd.lvm.lv=vg0/root resume=/dev/mapper/vg0-swap quiet")

    def options(self, cmdline=None, subvol="snapshots/42/snapshot"):
        return snapshot_options(cmdline or self.LUKS, subvol)

    def test_everything_needed_to_reach_the_disk_is_kept(self):
        options = self.options()
        for needed in ("root=UUID=4a93", "rd.luks.uuid=luks-3f24", "rd.lvm.lv=vg0/root"):
            self.assertIn(needed, options)

    def test_the_subvolume_is_replaced_and_other_rootflags_kept(self):
        options = self.options()
        self.assertIn("subvol=snapshots/42/snapshot", options)
        self.assertIn("compress=zstd:1", options)
        self.assertNotIn("subvol=root,", options)

    def test_always_read_only(self):
        self.assertIn(" ro ", f" {self.options()} ")
        self.assertNotIn(" rw ", f" {self.options()} ")
        self.assertIn(" ro ", f" {self.options('root=UUID=x rw')} ")

    def test_resume_is_dropped(self):
        """A hibernation image of the normal system must not land on a snapshot."""
        self.assertNotIn("resume=", self.options())

    def test_volatile_is_never_carried_over(self):
        """It hangs the boot: the initrd does not build the overlay."""
        cmdline = "root=UUID=x ro systemd.volatile=overlay"
        self.assertNotIn("systemd.volatile", self.options(cmdline))

    def test_a_unified_kernel_images_own_initrd_argument_is_dropped(self):
        """A Type #1 entry names the initrd in its own field; twice is wrong."""
        cmdline = (
            "initrd=\\e1b956a68b514aa9bbcce22e2e1fc1ab\\7.2.5-200.fc44.x86_64\\initrd "
            "root=UUID=x rw rd.luks.uuid=215f2849"
        )
        options = snapshot_options(cmdline, "snapshots/9/snapshot")
        self.assertNotIn("initrd=", options)
        self.assertIn("rd.luks.uuid=215f2849", options, "LUKS must survive")

    def test_a_transient_machine_id_is_dropped(self):
        """A UKI bakes it in; on a read-only root the commit service then fails."""
        cmdline = "root=UUID=x ro systemd.machine_id=0108a8f87e784af98bf70815ff87d439"
        self.assertNotIn("systemd.machine_id", self.options(cmdline))

    def test_a_rescue_command_line_does_not_compound(self):
        cmdline = "root=UUID=x ro rootflags=subvol=snapshots/31/snapshot"
        options = self.options(cmdline, "snapshots/7/snapshot")
        self.assertIn("subvol=snapshots/7/snapshot", options)
        self.assertNotIn("snapshots/31", options)

    def test_subvolid_is_replaced_too(self):
        cmdline = "root=UUID=x ro rootflags=subvolid=256"
        self.assertNotIn("subvolid", self.options(cmdline))


class EntryFileTests(unittest.TestCase):
    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.boot = Path(tmp.name)

    def test_kernel_files_finds_the_uki_layout(self):
        version, mid = "7.2.4-200.fc44.x86_64", "abc123"
        (self.boot / mid / version).mkdir(parents=True)
        (self.boot / mid / version / "linux").write_text("k")
        (self.boot / mid / version / "initrd").write_text("i")
        self.assertEqual(kernel_files(self.boot, mid, version),
                         (f"/{mid}/{version}/linux", f"/{mid}/{version}/initrd"))

    def test_kernel_files_finds_the_traditional_layout(self):
        version = "7.2.4-200.fc44.x86_64"
        (self.boot / f"vmlinuz-{version}").write_text("k")
        (self.boot / f"initramfs-{version}.img").write_text("i")
        self.assertEqual(kernel_files(self.boot, "abc123", version),
                         (f"/vmlinuz-{version}", f"/initramfs-{version}.img"))

    def test_kernel_files_missing_is_none(self):
        self.assertIsNone(kernel_files(self.boot, "abc123", "9.9.9"))

    def test_only_our_own_entries_are_recognised(self):
        entries = self.boot / "entries"
        entries.mkdir()
        for name in (f"{ENTRY_PREFIX}7.conf", f"{ENTRY_PREFIX}12.conf",
                     "fedora-7.2.4.conf", f"{ENTRY_PREFIX}notanumber.conf"):
            (entries / name).write_text("x")
        self.assertEqual(sorted(snapshot_entries(entries)), [7, 12])

    def test_entry_text_has_the_required_fields(self):
        text = entry_text("Snapshot 7", "7.2.4", "/l", "/i", "root=UUID=x ro")
        for key in ("title", "version", "linux", "initrd", "options", "sort-key"):
            self.assertRegex(text, rf"(?m)^{key}\s")


class SyncEntriesTests(unittest.TestCase):
    """The boot menu is shared: write only ours, remove only ours."""

    MID = "0108a8f87e784af98bf70815ff87d439"
    KERNEL = "7.2.4-200.fc44.x86_64"
    CMDLINE = "root=UUID=4a93 ro rootflags=subvol=root rd.luks.uuid=luks-3f24"

    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.boot = Path(tmp.name)
        self.entries = self.boot / "loader/entries"
        self.entries.mkdir(parents=True)
        images = self.boot / self.MID / self.KERNEL
        images.mkdir(parents=True)
        (images / "linux").write_text("kernel")
        (images / "initrd").write_text("initrd")

    def sync(self, wanted):
        return sync_snapshot_entries(
            self.entries, self.boot, wanted, self.MID, self.CMDLINE, "snapshots"
        )

    def test_writes_an_entry_per_snapshot(self):
        written, removed, skipped = self.sync([(7, self.KERNEL, "Snapshot 7")])
        self.assertEqual((written, removed, skipped), ([7], [], []))
        text = (self.entries / f"{ENTRY_PREFIX}7.conf").read_text()
        self.assertIn("subvol=snapshots/7/snapshot", text)
        self.assertIn("rd.luks.uuid=luks-3f24", text)
        self.assertIn(f"/{self.MID}/{self.KERNEL}/linux", text)

    def test_removes_entries_for_snapshots_that_are_gone(self):
        self.sync([(7, self.KERNEL, "Snapshot 7"), (8, self.KERNEL, "Snapshot 8")])
        written, removed, _ = self.sync([(8, self.KERNEL, "Snapshot 8")])
        self.assertEqual((written, removed), ([8], [7]))
        self.assertFalse((self.entries / f"{ENTRY_PREFIX}7.conf").exists())

    def test_never_touches_an_entry_it_did_not_write(self):
        theirs = self.entries / "fedora-7.2.4.conf"
        theirs.write_text("title Fedora\n")
        self.sync([])
        self.assertTrue(theirs.exists(), "kernel-install's entries are not ours to remove")
        self.assertEqual(theirs.read_text(), "title Fedora\n")

    def test_a_snapshot_whose_kernel_is_gone_is_skipped_not_promised(self):
        written, _, skipped = self.sync([(9, "9.9.9-gone", "Snapshot 9")])
        self.assertEqual((written, skipped), ([], [9]))
        self.assertFalse((self.entries / f"{ENTRY_PREFIX}9.conf").exists())

    def test_zero_wanted_clears_ours_only(self):
        self.sync([(7, self.KERNEL, "Snapshot 7")])
        (self.entries / "fedora.conf").write_text("x")
        _, removed, _ = self.sync([])
        self.assertEqual(removed, [7])
        self.assertTrue((self.entries / "fedora.conf").exists())

    def test_rewriting_an_unchanged_entry_leaves_the_file_alone(self):
        self.sync([(7, self.KERNEL, "Snapshot 7")])
        path = self.entries / f"{ENTRY_PREFIX}7.conf"
        before = path.stat().st_mtime_ns
        self.sync([(7, self.KERNEL, "Snapshot 7")])
        self.assertEqual(path.stat().st_mtime_ns, before, "no needless writes to the ESP")

    def test_entries_are_not_world_readable(self):
        self.sync([(7, self.KERNEL, "Snapshot 7")])
        mode = (self.entries / f"{ENTRY_PREFIX}7.conf").stat().st_mode & 0o777
        self.assertEqual(mode, 0o600)


class ImagePrefixTests(unittest.TestCase):
    """Which prefix kernel-install's entries put before the kernel path.

    Empty when /boot is its own partition, "/boot" when /boot is a directory or
    subvolume of the root filesystem. Getting it wrong hands GRUB a kernel it
    cannot find, and GRUB stops after "Welcome to GRUB!" saying nothing.
    """

    def setUp(self):
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        self.dir = Path(directory.name)

    def write(self, name, linux):
        (self.dir / name).write_text(
            f"title Fedora Linux\nversion 7.2.5\nlinux {linux}\ninitrd /x.img\noptions ro\n"
        )

    def test_a_separate_boot_partition_needs_no_prefix(self):
        self.write("abc-7.2.5.conf", "/vmlinuz-7.2.5")
        self.assertEqual(boot.image_prefix(self.dir), "")

    def test_boot_on_the_root_filesystem_needs_one(self):
        self.write("abc-7.2.5.conf", "/boot/vmlinuz-7.2.5")
        self.assertEqual(boot.image_prefix(self.dir), "/boot")

    def test_our_own_entries_are_ignored(self):
        # They would only repeat whatever was guessed last time.
        (self.dir / f"{boot.ENTRY_PREFIX}1.conf").write_text("linux /boot/vmlinuz-7.2.5\n")
        self.write("abc-7.2.5.conf", "/vmlinuz-7.2.5")
        self.assertEqual(boot.image_prefix(self.dir), "")

    def test_no_entries_at_all_falls_back_to_the_specification(self):
        self.assertEqual(boot.image_prefix(self.dir), "")

    def test_an_unreadable_entry_does_not_stop_the_search(self):
        bad = self.dir / "aaa-broken.conf"
        bad.write_text("linux \n")
        self.write("bbb-7.2.5.conf", "/boot/vmlinuz-7.2.5")
        self.assertEqual(boot.image_prefix(self.dir), "/boot")
